#############################################################################
# Makefile for building: mobileNetSSDTensorRT
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  mobileNetSSDTensorRT.pro
# Template: app
# Command: /home/lcg/Qt5.6.1/5.6/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile mobileNetSSDTensorRT.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iutil -I/usr/local/cuda/include -I/usr/local/cuda-8.0/include -I../../TensorRT-3.0.2/include -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I../../../Qt5.6.1/5.6/gcc_64/include -I../../../Qt5.6.1/5.6/gcc_64/include/QtGui -I../../../Qt5.6.1/5.6/gcc_64/include/QtCore -I. -I../../../Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /home/lcg/Qt5.6.1/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mobileNetSSDTensorRT1.0.0
DISTDIR = /home/lcg/Work/trrt_demo/mobileNetSSDTensorRT/.tmp/mobileNetSSDTensorRT1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/lcg/Qt5.6.1/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/cuda/lib64/ -L/usr/local/cuda/lib64 -lcublas -lcufft -lcurand -lnppc -lnvToolsExt -lcudart -lcufftw -lcusolver -lnppi -lcudnn -lcuinj64 -lcusparse -lnpps -L/home/lcg/Work/TensorRT-3.0.2/lib/ -lnvcaffe_parser -lnvinfer_plugin -lnvparsers -lnvinfer /usr/local/lib/libopencv_*.so -L/home/lcg/Qt5.6.1/5.6/gcc_64/lib -lQt5Gui -L/usr/lib64 -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		common.cpp \
		mathFunctions.cpp \
		pluginImplement.cpp \
		tensorNet.cpp \
		util/loadImage.cpp 
OBJECTS       = mathFunctions_cuda.o \
		kernel_cuda.o \
		main.o \
		common.o \
		mathFunctions.o \
		pluginImplement.o \
		tensorNet.o \
		loadImage.o
DIST          = mathFunctions.cu \
		kernel.cu \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/resources.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/moc.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/lex.prf \
		mobileNetSSDTensorRT.pro common.h \
		cudaUtility.h \
		mathFunctions.h \
		pluginImplement.h \
		tensorNet.h \
		cuda/cudaUtility.h \
		util/loadImage.h main.cpp \
		common.cpp \
		mathFunctions.cpp \
		pluginImplement.cpp \
		tensorNet.cpp \
		util/loadImage.cpp
QMAKE_TARGET  = mobileNetSSDTensorRT
DESTDIR       = 
TARGET        = mobileNetSSDTensorRT


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mobileNetSSDTensorRT.pro ../../../Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/resources.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/moc.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/lex.prf \
		mobileNetSSDTensorRT.pro \
		../../../Qt5.6.1/5.6/gcc_64/lib/libQt5Gui.prl \
		../../../Qt5.6.1/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile mobileNetSSDTensorRT.pro
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/unix.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/linux.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/qconfig.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/default_post.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/qt.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/resources.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/moc.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/yacc.prf:
../../../Qt5.6.1/5.6/gcc_64/mkspecs/features/lex.prf:
mobileNetSSDTensorRT.pro:
../../../Qt5.6.1/5.6/gcc_64/lib/libQt5Gui.prl:
../../../Qt5.6.1/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile mobileNetSSDTensorRT.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mathFunctions.cu kernel.cu $(DISTDIR)/
	$(COPY_FILE) --parents common.h cudaUtility.h mathFunctions.h pluginImplement.h tensorNet.h cuda/cudaUtility.h util/loadImage.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp common.cpp mathFunctions.cpp pluginImplement.cpp tensorNet.cpp util/loadImage.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_cuda_d_make_all: mathFunctions_cuda.o kernel_cuda.o
compiler_cuda_d_clean:
	-$(DEL_FILE) mathFunctions_cuda.o kernel_cuda.o
mathFunctions_cuda.o: mathFunctions.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cublas_v2.h \
		/usr/local/cuda/include/cublas_api.h \
		/usr/local/cuda/include/cuComplex.h \
		/usr/local/cuda/include/cuda_fp16.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/curand.h \
		cudaUtility.h \
		mathFunctions.cu
	/usr/local/cuda/bin/nvcc -g -D_DEBUG --use_fast_math -I"/home/lcg/Work/trrt_demo/mobileNetSSDTensorRT/util" -I"/usr/local/cuda/include" -lcudart -lcufft --machine 64 -arch=sm_50 -c -o mathFunctions_cuda.o mathFunctions.cu

kernel_cuda.o: util/cuda/cudaUtility.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cuda.h \
		kernel.cu
	/usr/local/cuda/bin/nvcc -g -D_DEBUG --use_fast_math -I"/home/lcg/Work/trrt_demo/mobileNetSSDTensorRT/util" -I"/usr/local/cuda/include" -lcudart -lcufft --machine 64 -arch=sm_50 -c -o kernel_cuda.o kernel.cu

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_d_clean 

####### Compile

main.o: main.cpp common.h \
		../../TensorRT-3.0.2/include/NvInfer.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		cudaUtility.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cuda.h \
		mathFunctions.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/cublas_v2.h \
		/usr/local/cuda/include/cublas_api.h \
		/usr/local/cuda/include/cuComplex.h \
		/usr/local/cuda/include/cuda_fp16.h \
		/usr/local/cuda/include/curand.h \
		pluginImplement.h \
		../../TensorRT-3.0.2/include/NvCaffeParser.h \
		../../TensorRT-3.0.2/include/NvInferPlugin.h \
		tensorNet.h \
		util/loadImage.h \
		util/cuda/cudaUtility.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/QList \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/QFile \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qfile.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/QDir \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qdir.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qhash.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/QDebug \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qdebug.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qmap.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qlocale.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qvariant.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qset.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/QTime \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

common.o: common.cpp common.h \
		../../TensorRT-3.0.2/include/NvInfer.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

mathFunctions.o: mathFunctions.cpp mathFunctions.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cublas_v2.h \
		/usr/local/cuda/include/cublas_api.h \
		/usr/local/cuda/include/cuComplex.h \
		/usr/local/cuda/include/cuda_fp16.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/curand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mathFunctions.o mathFunctions.cpp

pluginImplement.o: pluginImplement.cpp pluginImplement.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cublas_v2.h \
		/usr/local/cuda/include/cublas_api.h \
		/usr/local/cuda/include/cuComplex.h \
		/usr/local/cuda/include/cuda_fp16.h \
		../../TensorRT-3.0.2/include/NvCaffeParser.h \
		../../TensorRT-3.0.2/include/NvInfer.h \
		../../TensorRT-3.0.2/include/NvInferPlugin.h \
		mathFunctions.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/curand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pluginImplement.o pluginImplement.cpp

tensorNet.o: tensorNet.cpp tensorNet.h \
		pluginImplement.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cublas_v2.h \
		/usr/local/cuda/include/cublas_api.h \
		/usr/local/cuda/include/cuComplex.h \
		/usr/local/cuda/include/cuda_fp16.h \
		../../TensorRT-3.0.2/include/NvCaffeParser.h \
		../../TensorRT-3.0.2/include/NvInfer.h \
		../../TensorRT-3.0.2/include/NvInferPlugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tensorNet.o tensorNet.cpp

loadImage.o: util/loadImage.cpp util/loadImage.h \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		util/cuda/cudaUtility.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/device_functions.h \
		/usr/local/cuda/include/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/device_double_functions.h \
		/usr/local/cuda/include/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/common_functions.h \
		/usr/local/cuda/include/math_functions.h \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_functions_decls.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/math_functions.hpp \
		/usr/local/cuda/include/math_functions_dbl_ptx3.h \
		/usr/local/cuda/include/math_functions_dbl_ptx3.hpp \
		/usr/local/cuda/include/device_launch_parameters.h \
		/usr/local/cuda/include/cuda.h \
		util/cuda/cudaMappedMemory.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/QImage \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qimage.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qcolor.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qrgb.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qglobal.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qconfig.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qisenum.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qlogging.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qflags.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qmutex.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qiterator.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qchar.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qpair.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstring.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qregexp.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qrect.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qmargins.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qsize.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qpoint.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qtransform.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qvector.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qregion.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobject.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtCore/qline.h \
		../../../Qt5.6.1/5.6/gcc_64/include/QtGui/qpainterpath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadImage.o util/loadImage.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

